networks:
  default:
    name: adaos

services:
  rasa:
    image: rasa/rasa:latest
    # restart: unless-stopped
    volumes:
      - ./rasa:/app
    ports:
      - 5005:5005
    command: run -m models --enable-api --cors "*" --debug
  
  rasa-actions:
    build: 
      context: ./rasa
      dockerfile: actions.Dockerfile
    # restart: unless-stopped
    volumes: 
      - ./rasa/actions:/app/actions
    ports: 
      - 5055:5055

  whisper:
    build:
      context: ./voice
      dockerfile: Dockerfile
    # restart: unless-stopped
    ports:
      - "8000:8000"